### ISSUE TITLE
Bug about the evaluation code of CUTS

### ISSUE THREAD

**Issue by zhjcp** [jarrycyx/UNN#1]
Hello, the code you provided to calculate TN seems to be incorrect. You used ' np.mean((1-causal_graph) * (1-causal_graph)) ' instead of ' np.mean((1-causal_graph) * (1-true_cm)) ', which should be used to calculate TN. (Refer to line-43 in misc.py) .

**Comment by jarrycyx** [comment]
Bug's fixed. Thanks!
