### ISSUE TITLE
dimension of input time series dataset

### ISSUE THREAD

**Issue by zeyevv** [jarrycyx/UNN#11]
Dear developer,
Thanks for sharing this repository. I was deeply inspired by your paper. I have a question about the dimension of input time series dataset. For example, when we trainning the model on the DREAM dataset, is the input 3-D (variables×slices×length) or 2-D (variables×(slices×length))? The first approach is to think of number of slices as minibatches.

**Comment by jarrycyx** [comment]
The input is  2-D (variables×(slices×length)). However, for Dream dataset consider set sota.cuts_plus_cyx.block_size to 21.

**Comment by zeyevv** [comment]
Thanks for your reply. I have another question about model training. When I tested CUTS using the DREAm dataset, I found that AUC always rises first and then falls. Is this phenomenon normal? Are there any other metrics to measure the effectiveness of causal inference？
