### ISSUE TITLE
Is it Possible to Train/Run the model without GroundTruth

### ISSUE THREAD

**Issue by SaqibMamoon** [jarrycyx/UNN#3]
Dear Authors,

I would like to ask is there a available settings or possibility that CUTS_Plus could be trained to without causal groundtruth graphs. So in this cases we can save the graphs generated by the model, and use svm to classify like for gender classification? 

Thanks a lot,

**Comment by jarrycyx** [comment]
Yes, it's possible. The only modification would be setting true_cm=None for train() in [cuts_plut.py](https://github.com/jarrycyx/UNN/blob/main/CUTS_Plus/cuts_plus.py) and ignore the auc score.
